
import { ChatMessage } from '../types';

// The different stages of the onboarding conversation
export type OnboardingState = 'START' | 'AWAITING_STORY' | 'AWAITING_PASSION' | 'AWAITING_ICS' | 'AWAITING_RITUALS' | 'DONE';

// The canned responses for each stage
const responses: Record<OnboardingState, string> = {
    'START': `Hi, I'm the Guild Registrar. To forge your Adventurer's Profile, I need to know about your main quest. 
    
Tell me a bit about yourself professionally. (e.g., your major, your year, and what you're thinking about for a career).`,
    
    'AWAITING_STORY': `Interesting. Now, what are you passionate about? This is the most important part. Are you:

1.  **Undeclared**: (Just exploring options)
2.  **Passionate Major**: (Love your major, not sure what jobs exist)
3.  **Passionate Industry**: (e.g., 'I want to work in Biotech/Gaming')
4.  **Hyper-Specific**: (e.g., 'I want to be a Technical Advisor for a VC firm')`,

    'AWAITING_PASSION': `Got it. To see your 'Main Quests' and deadlines, I need your calendar feed. 
    
Please go to Canvas (or Google Calendar) and paste your secret iCal (.ics) link here.`,

    'AWAITING_ICS': `Perfect. Last question: What 'Daily Rituals' or tasks do you do every day? 
    
(e.g., 'Go to the gym for 1 hour,' 'Read for 30 mins,' 'Walk the dog').`,

    'AWAITING_RITUALS': `Your Adventurer's Profile is forged and saved. Your first 'Bounty Board' (your 9-5 schedule) will be generated by the Dungeon Master every morning. Welcome to the guild.`,

    'DONE': "I have all the information I need, Adventurer. You are ready to begin your journey!"
};

// A map to determine the next state in the conversation flow
export const nextOnboardingState: Record<OnboardingState, OnboardingState> = {
    'START': 'AWAITING_STORY',
    'AWAITING_STORY': 'AWAITING_PASSION',
    'AWAITING_PASSION': 'AWAITING_ICS',
    'AWAITING_ICS': 'AWAITING_RITUALS',
    'AWAITING_RITUALS': 'DONE',
    'DONE': 'DONE',
};

/**
 * Retrieves the agent's message for a given onboarding state.
 * @param state The current state of the onboarding conversation.
 * @returns A ChatMessage object with the agent's response.
 */
export const getOnboardingResponse = (state: OnboardingState): ChatMessage => {
    return {
        id: `agent-${Date.now()}`,
        sender: 'agent',
        text: responses[state],
    };
};
