
import { ChatMessage } from '../types';

let conversationState: 'START' | 'AWAITING_STORY' | 'AWAITING_PASSION' | 'AWAITING_ICS' | 'AWAITING_RITUALS' | 'DONE' = 'START';

const responses = {
    GREET: `Hi, I'm the Guild Registrar. To forge your Adventurer's Profile, I need to know about your main quest. 
    
Tell me a bit about yourself professionally. (e.g., your major, your year, and what you're thinking about for a career).`,
    
    ASK_PASSION: `Interesting. Now, what are you passionate about? This is the most important part. Are you:

1.  **Undeclared**: (Just exploring options)
2.  **Passionate Major**: (Love your major, not sure what jobs exist)
3.  **Passionate Industry**: (e.g., 'I want to work in Biotech/Gaming')
4.  **Hyper-Specific**: (e.g., 'I want to be a Technical Advisor for a VC firm')`,

    ASK_ICS: `Got it. To see your 'Main Quests' and deadlines, I need your calendar feed. 
    
Please go to Canvas (or Google Calendar) and paste your secret iCal (.ics) link here.`,

    ASK_RITUALS: `Perfect. Last question: What 'Daily Rituals' or tasks do you do every day? 
    
(e.g., 'Go to the gym for 1 hour,' 'Read for 30 mins,' 'Walk the dog').`,

    CONCLUDE: `Your Adventurer's Profile is forged and saved. Your first 'Bounty Board' (your 9-5 schedule) will be generated by the Dungeon Master every morning. Welcome to the guild.`
};

export const getOnboardingResponse = (userInput: string): Promise<ChatMessage> => {
    return new Promise(resolve => {
        let responseText = '';

        switch (conversationState) {
            case 'START':
                responseText = responses.GREET;
                conversationState = 'AWAITING_STORY';
                break;
            case 'AWAITING_STORY':
                responseText = responses.ASK_PASSION;
                conversationState = 'AWAITING_PASSION';
                break;
            case 'AWAITING_PASSION':
                responseText = responses.ASK_ICS;
                conversationState = 'AWAITING_ICS';
                break;
            case 'AWAITING_ICS':
                responseText = responses.ASK_RITUALS;
                conversationState = 'AWAITING_RITUALS';
                break;
            case 'AWAITING_RITUALS':
                responseText = responses.CONCLUDE;
                conversationState = 'DONE';
                break;
            case 'DONE':
                responseText = "I have all the information I need, Adventurer. You are ready to begin your journey!";
                break;
        }

        resolve({
            id: `agent-${Date.now()}`,
            sender: 'agent',
            text: responseText,
        });
    });
};
